# Generated by Django 5.1.6 on 2025-02-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.CharField(default="ProductId(value='00b0754b-f4de-4546-86e3-e9ff0c6f2698')", editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
